# Generated by Django 4.0.6 on 2022-07-25 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('priority', models.CharField(max_length=255)),
                ('date_of_delivery', models.DateField()),
                ('comment', models.TextField(max_length=255)),
            ],
        ),
    ]
