# Generated by Django 4.0.6 on 2022-07-29 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_manager', '0002_task_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.AlterField(
            model_name='task',
            name='comment',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('H', 'High'), ('M', 'Medium'), ('L', 'Low')], max_length=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('BL', 'Backlog'), ('TD', 'To_Do'), ('DI', 'Doing'), ('TS', 'Test'), ('DN', 'Done')], max_length=2),
        ),
    ]
