# Generated by Django 4.0.6 on 2022-07-29 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_manager', '0003_remove_task_user_alter_task_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('H', 'High'), ('M', 'Medium'), ('L', 'Low')], default='LOW', max_length=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('BL', 'Backlog'), ('TD', 'To_Do'), ('DI', 'Doing'), ('TS', 'Test'), ('DN', 'Done')], default='BACKLOG', max_length=2),
        ),
    ]
